recipe-line-1: '#11'
recipe-line-2: '231'
recipe-line-3: '32#'
# for an empty slot use #
item-1: "STRING"
item-2: "PAPER"
item-3: "IRON_INGOT"
item-4: "AIR"
item-5: "AIR"
item-6: "AIR"
item-7: "AIR"
item-8: "AIR"
item-9: "AIR"
#
#This plugin is brought to you by play.cidermc.com