recipe-line-1: '#1#'
recipe-line-2: '121'
recipe-line-3: '345'
# for an empty slot use #
item-1: "DIAMOND"
item-2: "GOLD_INGOT"
item-3: "IRON_INGOT"
item-4: "EMERALD"
item-5: "NETHERITE_INGOT"
item-6: "AIR"
item-7: "AIR"
item-8: "AIR"
item-9: "AIR"
#
#This plugin is brought to you by play.cidermc.com